[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "textstat-seminar-kiolsmirnov"
version = "0.1.0"
description = "Simple text statistics CLI package"
readme = "README.md"

requires-python = ">=3.10"
authors = [{ name = "Kirill Smirnov", email = "student@example.com" }]
license = "MIT"
license-files = ["LICENSE"]
keywords = ["text", "statistics", "cli", "education"]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Education",
  "Programming Language :: Python :: 3",
  "Topic :: Text Processing :: Linguistic",
]

dependencies = []

[project.urls]
Homepage = "https://github.com/DanielShinoda/ami_advanced_python_seminars_26f"

[project.scripts]
textstat = "textstat_seminar.cli:main"

[tool.setuptools.package-data]
textstat_seminar = ["data/*.txt"]